baseURL: "https://jurjenbloo.github.io/dbleu/"
title: "D'Bleu | Navigating Change. Leading with Purpose. Delivering Results."
summaryLength: 20

# services:
#   googleAnalytics:
#     id: G-MEASUREMENT_ID

