baseURL: "https://jurjenbloo.github.io/dbleu/"
title: "D'Bleu | Navigating Change. Leading with Purpose. Delivering Results."
languageCode: "en-us"
summaryLength: 20

enableRobotsTXT: true   # auto-builds robots.txt
canonifyURLs: true      # forces canonical
enableGitInfo: true     # git dates in front-matter

# Optional: Google Analytics
# services:
#   googleAnalytics:
#     id: "G-XXXXXXXXXX"