main:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Our Approach"
    url: "/approach/"
    weight: 2

#  - name: "Our team"
#    url: "/#"
#    weight: 3

#  - name: "Pricing"
#    url: "/#"
#    weight: 4

#  - name: "Insights"
#    url: "/blog"
#    weight: 5

buttons:
  - name: "Schedule a call"
    url: "/#"
    weight: 5

footer:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Our Approach"
    url: "/approach/"
    weight: 2

#  - name: "Our team"
#    url: "/#"
#    weight: 3

#  - name: "Pricing"
#    url: "/#"
#    weight: 4

#  - name: "Insights"
#    url: "/blog"
#    weight: 5
