title: "D'Bleu"
description: |
  Navigating Change. <br>
  Leading with <strong class=\"text-pink-500\">Purpose</strong>.<br>
  Delivering <strong class=\"text-pink-500\">Results</strong>.

items: 
  - "images/hero-image.png"

logo: "arrow-up.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  linkedin: "https://www.linkedin.com/company/dbleu/"

location:
  - "Netherlands"

contact:
  - "jurjen@dbleu.nl"
  - "+31610899925"

copyright: "Copyright 2025 D'Bleu"

