title: "Up Business"
description: "test"
items: 
  - "images/hero-image.png"

logo: "arrow-up.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  dribbble: "#"
  instagram: "#"
  facebook: "#"
  twitter: "#"

location:
  - "3891 Ranchview Dr. Richardson, California 62639"
  - "4517 Washington Ave. Manchester, Kentucky 39495"

contact:
  - "jurjen@dbleu.nl"
  - "+31610899925"

copyright: "© 2022 Up Business All Rights Reserved"

