title: "D'Bleu"
description: |
  Navigating Change. <br>
  Leading with <strong class=\"text-pink-500\">Purpose</strong>.<br>
  Delivering <strong class=\"text-pink-500\">Results</strong>.

images:
  - "images/og-cover.jpg"     # default OG & Twitter image

logo: "images/arrow-up.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  linkedin: "https://www.linkedin.com/company/dbleu/"
  twitter: "@jurjenbloo"

organisation: "D’Bleu"

location:
  - "Netherlands"

contact:
  - "jurjen@dbleu.nl"
  - "+31 6 1089 9925"

copyright: "© 2025 D’Bleu. All rights reserved."